In [1]:
print("HI")

HI


In [2]:
import torch 
import torch.nn as nn

In [4]:
seq_len= 5
d_model = 8

In [5]:
a = torch.zeros(seq_len, d_model)
a

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
a.shape, a.ndim

(torch.Size([5, 8]), 2)

In [27]:
a[:, 0::2]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
a.unsqueeze(1)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]]])

In [30]:
a.unsqueeze(0)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [32]:
a.unsqueeze(0).shape

torch.Size([1, 5, 8])

In [37]:
a.unsqueeze(0)[:, :5, : ]

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [9]:
# position
b= torch.arange(0, seq_len, dtype=torch.float)
b

tensor([0., 1., 2., 3., 4.])

In [13]:
b.shape, b.ndim

(torch.Size([5]), 1)

In [14]:
c= b.unsqueeze(1)
c

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [15]:
c.shape, c.ndim

(torch.Size([5, 1]), 2)

In [22]:
torch.arange(0, d_model, 2).float()

tensor([0., 2., 4., 6.])